version: "3.6"

services:
  ssr:
    image: teddysun/shadowsocks-r:latest
    restart: always
    container_name: ssr
    ports: 
      - 4041:4041/tcp
      - 4041:4041/udp
    networks:
      - ssr
    volumes:
      - "./etc/:/etc/shadowsocks-r"
    #restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
        max-file: "10"

networks:
  ssr:
    name: ssr
    driver: bridge
